version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gato_comics_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-gatocomicspass}
      POSTGRES_DB: ${DB_NAME:-gatocomics}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gato-network

volumes:
  postgres_data:

networks:
  gato-network:
    driver: bridge